### ISSUE TITLE
Puppet 4 testing

### ISSUE THREAD

**Issue by razorsedge** [rodjek/rspec-puppet#263]
I am attempting to test my modules via Travis-CI on Puppet 4 (4.0.0-rc1) and am running into a slew of errors.

Module code: https://github.com/razorsedge/puppet-snmp/tree/develop
Travis-CI config: https://github.com/razorsedge/puppet-snmp/blob/develop/.travis.yml#L38-L39

This is one of the errors:
```
1) snmp::client on a supported osfamily, default parameters for osfamily RedHat, operatingsystem RedHat should contain Package[snmp-client] with ensure => "present" and name => "net-snmp-utils"
   Failure/Error: it { should contain_package('snmp-client').with(
   NoMethodError:
     undefined method `setdefaults' for #<Puppet::Settings:0x00000001fa2430>
   # ./spec/classes/snmp_client_spec.rb:38:in `block (5 levels) in <top (required)>'
```
Full log: https://travis-ci.org/razorsedge/puppet-snmp/jobs/55598752

Is this something that I need to fix in my code (and any hints as to what/where), or something with rspec-puppet not working with Puppet 4?

**Comment by electrical** [comment]
Caused by https://github.com/rodjek/rspec-puppet/blob/master/lib/rspec-puppet/support.rb#L123-L147
Caused by commit https://github.com/puppetlabs/puppet/commit/ecdef20ace811b41cb0e9077376e256f70c7a331
Solution seems to be to call `define_settings`

@razorsedge i could setup a fork of the master branch and make the change if you want to try it out?

**Comment by domcleal** [comment]
It's only hitting that rescue block and calling setdefaults because some of those settings no longer exist.  I think rspec-puppet needs to stop setting:

1. manifestdir
1. templatedir
1. parser

**Comment by razorsedge** [comment]
@electrical Yes, please.  I will give it a go this weekend.

**Comment by electrical** [comment]
Create https://github.com/electrical/rspec-puppet/tree/puppet4

Feel free to try it out.
I did try out the rspec-puppet spec tests but failed all over the place.
Trying to do some discovery on that.

**Comment by electrical** [comment]
Been trying to get it to work but not much luck.
Managed to fix some of the stuff but not much so far

**Comment by razorsedge** [comment]
@electrical Strangely, your puppet4 branch looks just like the master.  Am I missing something?

**Comment by rb2k** [comment]
I think this might be the same problem as in my issue over at https://github.com/rodjek/rspec-puppet/issues/255 ?

**Comment by hunner** [comment]
#265 with additional changes. Still missing function API updates

**Comment by madAndroid** [comment]
Just to add to the mix here: we're using [hiera-puppet-helper](https://github.com/bobtfish/hiera-puppet-helper) to assist with hiera lookups during our spec tests .. works fine under 3.x, but hiera calls fail on 4.x - is that possibly as a result of the missing function API updates @hunner mentioned?

**Comment by razorsedge** [comment]
Version [2.1.0](https://github.com/rodjek/rspec-puppet/releases/tag/v2.1.0) shipped yesterday and fixes my problems.

**Comment by igalic** [comment]
\o/
